# Generated by Django 4.2.2 on 2023-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfarmerlinker',
            name='started_on',
            field=models.DateField(help_text='Date the farmer started farming this farm', null=True),
        ),
        migrations.AlterField(
            model_name='farmfarmerlinker',
            name='stopped_on',
            field=models.DateField(help_text='Date the farmer stopped farming this farm', null=True),
        ),
        migrations.AlterField(
            model_name='farmfieldlinker',
            name='acquired_on',
            field=models.DateField(help_text='Date the field was made part of the farm', null=True),
        ),
        migrations.AlterField(
            model_name='farmfieldlinker',
            name='removed_on',
            field=models.DateField(help_text='Date the field was removed from the farm', null=True),
        ),
    ]
